### ISSUE TITLE
您好，我是vue-activiti-demo仓库的所有者griabcrh，现在这个仓库代码涉及侵权，麻烦您将这个仓库删除，谢谢您的配合

### ISSUE THREAD

**Issue by griabcrh** [Zehrex/DD2476-Project#1]
您好，我是vue-activiti-demo仓库的所有者griabcrh，现在这个仓库代码涉及侵权，麻烦您将这个仓库删除，谢谢您的配合

**Comment by griabcrh** [comment]
您好，我是vue-activiti-demo这个仓库的创建者，也就是您这个项目参考的代码。因项目中涉及侵权代码，而您参考时并没有将侵权标志删除，所以我联系您删除,例如这个类的开头注释：https://github.com/BadrOuannas/DD2476-Project/blob/d921624366c01e29063718ee938af35d643c74b1/Crawler/data/StrAttri.java

**Comment by BadrOuannas** [comment]
The files are deleted, next time contact in english I don't speak chinese!

**Comment by griabcrh** [comment]
thank you very much

**Comment by Zehrex** [comment]
You are welcome :)
